# Mem-Agent Configuration File
# Edit this file according to your needs

# Usage Mode: "personal" or "business"
usage_mode: "business"  # personal or business

# Additional settings for Business mode
business:
  company_name: "Our Company"
  departments:
    - "Customer Service"
    - "Sales"
    - "Technical Support"
    - "HR"
  user_roles:
    - "admin"
    - "manager"
    - "employee"
    - "customer"
  enable_multi_user: true
  enable_reporting: true
  enable_api_integration: true
  security_level: "high"  # low, medium, high

# Additional settings for Personal mode
personal:
  user_name: "User"
  enable_reminders: true
  enable_personal_notes: true
  privacy_level: "high"  # low, medium, high
  share_data: false

# LLM Settings
llm:
  model: "granite4:tiny-h"
  base_url: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 500
  
# Memory Settings
memory:
  # "json" or "sql"
  backend: "sql"
  
  # For JSON backend
  json_dir: "memories"
  
  # For SQL backend
  db_path: "memories.db"
  
  # Memory limits
  max_conversations_per_user: 1000
  auto_cleanup: true
  cleanup_after_days: 90

# System Prompt Template
# Available templates: customer_service, tech_support, sales_assistant,
#                      education_tutor, health_advisor, personal_assistant,
#                      booking_assistant, hr_assistant
prompt:
  template: "customer_service"
  
  # Template variables (may vary for each template)
  variables:
    company_name: "Our Company"
    tone: "friendly and professional"
    
  # Custom prompt (can be used instead of template)
  custom_prompt: null

# Knowledge Base
knowledge_base:
  enabled: true
  
  # Auto-loading
  auto_load: true
  default_kb: "ecommerce"  # ecommerce, tech_support, or custom
  
  # Custom knowledge base file
  custom_kb_file: null  # "knowledge_samples/my_kb.json"
  
  # Search settings
  search_limit: 5
  min_relevance_score: 0.3

# Response Settings
response:
  # Knowledge base usage
  use_knowledge_base: true
  
  # Memory usage
  use_memory: true
  recent_conversations_limit: 5
  
  # Response format
  format:
    include_greeting: true
    include_follow_up: true
    max_length: 500
    
# Güvenlik ve Gizlilik
security:
  # Hassas bilgi filtreleme
  filter_sensitive_data: true
  sensitive_keywords:
    - "kredi kartı"
    - "şifre"
    - "parola"
    - "CVV"
    - "TC kimlik"
    
  # Rate limiting (dakikada maksimum istek)
  rate_limit:
    enabled: true
    max_requests_per_minute: 60
    max_requests_per_user_per_minute: 10

# Loglama
logging:
  enabled: true
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "mem_agent.log"
  max_size_mb: 10
  backup_count: 5
  
  # Hassas bilgileri loglama
  log_user_messages: true
  log_bot_responses: true
  mask_sensitive: true

# Performans
performance:
  # Cache ayarları
  enable_cache: true
  cache_ttl_seconds: 3600
  
  # Paralel işleme
  enable_parallel: false
  max_workers: 4

# İstatistikler ve Analytics
analytics:
  enabled: true
  
  # Metrikler
  track_response_time: true
  track_user_satisfaction: false
  track_conversation_length: true
  
  # Export
  export_interval_hours: 24
  export_path: "analytics"

# Özelleştirilmiş Ayarlar
custom:
  # Buraya kendi ayarlarınızı ekleyebilirsiniz
  feature_flags:
    enable_sentiment_analysis: false
    enable_auto_translation: false
    enable_voice_support: false
  
  # Entegrasyon bilgileri
  integrations:
    slack: null
    discord: null
    whatsapp: null

